---
name: sample-webapp-using-redis

addons:
- name: bpm
  jobs:
  - name: bpm
    release: bpm

instance_groups:
- name: redis
  azs: [z1]
  instances: 1
  vm_type: default
  stemcell: default
  persistent_disk: 10240
  networks: [{name: default}]
  jobs:
  - name: redis
    release: redis
    properties:
      password: ((redis-password))
- name: webapp
  azs: [z1, z2, z3]
  instances: 1
  vm_type: default
  stemcell: default
  networks: [{name: default}]
  jobs:
  - name: sample-webapp-using-redis
    release: sample-webapp-using-redis
    properties: {}

variables:
- name: redis-password
  type: password

stemcells:
- alias: default
  os: ubuntu-xenial
  version: 456.latest

update:
  canaries: 1
  canary_watch_time: 1000-60000
  update_watch_time: 1000-60000
  max_in_flight: 1
  serial: false

releases:
- name: bpm
  sha1: f2bd126b17b3591160f501d88d79ccf0aba1ae54
  url: git+https://github.com/cloudfoundry-incubator/bpm-release
  version: 1.0.4
- name: redis
  sha1: 9ad77d700cf773ae47328c99eddb80d83648b57d
  stemcell:
    os: ubuntu-xenial
    version: "456.3"
  url: https://s3.amazonaws.com/redis-boshrelease/compiled-releases/redis/redis-15.3.3-ubuntu-xenial-456.3-20190815-004641-067837581-20190815004641.tgz
  version: 15.3.3
- name: sample-webapp-using-redis
  sha1: 8b8ee8ff9d225046bc5b0fc06ef7c94dc172f834
  stemcell:
    os: ubuntu-xenial
    version: "456.58"
  url: https://github.com/cloudfoundry-community/sample-webapp-using-redis-boshrelease/releases/download/v1.0.2/sample-webapp-using-redis-1.0.2.tgz
  version: 1.0.2
