- type: remove
  path: /releases/name=redis/sha1
- type: replace
  path: /releases/name=redis/url
  value: {{ .Values.releases.defaults.url | quote }}
- type: replace
  path: /releases/name=redis/stemcell
  value:
    os: {{ .Values.releases.defaults.stemcell.os | quote }}
    version: {{ .Values.releases.defaults.stemcell.version | quote }}
