apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{- include "quarks.fullname" . -}}-bosh-manifest"
  labels:
    {{- include "quarks.labels" . | nindent 4 }}
data:
  manifest: |-
    {{- .Files.Get "assets/sample-webapp-using-redis.yml" | nindent 4 }}
