{{- $root := . -}}
{{- $fullname := (include "quarks.fullname" $root) -}}
---
apiVersion: {{ .Values.quarks.apiVersion }}
kind: BOSHDeployment
metadata:
  name: {{ include "quarks.fullname" . }}
  labels:
    {{- include "quarks.labels" . | nindent 4 }}
spec:
  manifest:
    name: "{{- include "quarks.fullname" . -}}-bosh-manifest"
    type: configmap
  ops:
{{- range $path, $bytes := .Files.Glob "assets/operations/*" }}
  - name: {{ include "quarks.ops-name" (dict "OpsPath" $path "Fullname" $fullname) }}
    type: configmap
{{- end }}
{{- range $_, $ops := .Values.operations.custom }}
  - name: {{ $ops | quote }}
    type: configmap
{{- end }}
