# This template creates a ConfigMap for each ops file under assets/operations.
{{- define "quarks.ops" -}}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "quarks.ops-name" .Path }}
  labels:
    app.kubernetes.io/component: operations
    # missing labels as .Chart.Name fails for unknown reason
data:
  ops: |-
    {{- tpl (.Root.Files.Get .Path) .Root | nindent 4 -}}
{{- end -}}

{{- $root := . -}}
{{- range $path, $bytes := .Files.Glob "assets/operations/*" }}
{{ include "quarks.ops" (dict "Root" $root "Path" $path) }}
{{- end }}
