---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name | quote }}
  labels:
    {{- include "quarks.labels" . | nindent 4 }}
    app.kubernetes.io/component: "service"
spec:
  type: {{ .Values.service.type }}
  selector:
    quarks.cloudfoundry.org/instance-group-name: webapp
    quarks.cloudfoundry.org/deployment-name: {{ .Values.deployment_name }}
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: 8080
