quarks:
  apiVersion: fissile.cloudfoundry.org/v1alpha1

releases:
  # The defaults for all releases, where we do not otherwise override them.
  defaults:
    webapp:
      url: docker.io/cfcommunity
      stemcell:
        os: opensuse-42.3 # stemcell.os UPDATED BY CI
        version: 38.g82067a9-30.95-7.0.0_360.g0ec8d681 # stemcell.version UPDATED BY CI
    redis:
      url: docker.io/cfcommunity
      stemcell:
        os: opensuse-42.3 # stemcell.os UPDATED BY CI
        version: 38.g82067a9-30.95-7.0.0_354.gacefcfa4 # stemcell.version UPDATED BY CI

service:
  type: ClusterIP
  port: 8080

cluster:
  instances: 1

operations:
  # A list of configmap names that should be applied to the BOSH manifest.
  custom: []
